name: Publish release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:

  github:
    name: github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Publish release
        uses: eloquent/github-release-action@v3
        if: github.ref_type == 'tag'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: "true"

  pypi:
    name: pypi
    runs-on: ubuntu-latest
    needs: github
    steps:
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Install flit
        run: |
          python -m pip install --upgrade pip
          pip install flit
      - name: Publish release
        env:
          FLIT_INDEX_URL: https://upload.pypi.org/legacy/
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: flit publish
